# Generated by Django 5.2.14 on 2026-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('context_used', models.TextField(blank=True)),
                ('chat_model', models.CharField(blank=True, max_length=120)),
                ('embed_model', models.CharField(blank=True, max_length=120)),
                ('top_k', models.PositiveIntegerField(default=0)),
                ('matches_found', models.PositiveIntegerField(default=0)),
                ('retrieval_ms', models.PositiveIntegerField(default=0)),
                ('llm_ms', models.PositiveIntegerField(default=0)),
                ('total_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
