# Generated by Django 5.2.14 on 2026-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_code', models.CharField(db_index=True, default='MA000100', max_length=20)),
                ('part', models.CharField(blank=True, max_length=300)),
                ('clause_no', models.CharField(blank=True, db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['clause_no', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('award_code', 'clause_no', 'chunk_index'), name='unique_clause_chunk')],
            },
        ),
    ]
