# Generated by Django 5.2.14 on 2026-05-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('information', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=60)),
                ('source_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
    ]
