# Generated by Django 5.2.14 on 2026-05-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_publicholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDISDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, help_text="Fiscal year label, e.g. '2024-25'.", max_length=20)),
                ('version', models.CharField(blank=True, help_text="e.g. 'v1.3'.", max_length=40)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('source_file', models.CharField(blank=True, help_text='Original filename / path of the ingested PDF.', max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are searched by the NDIS chat endpoint.')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-version'],
                'constraints': [models.UniqueConstraint(fields=('year', 'version'), name='unique_ndis_year_version')],
            },
        ),
        migrations.CreateModel(
            name='NDISChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=300)),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('is_indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='awards.ndisdocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_ndis_doc_chunk')],
            },
        ),
    ]
