# Generated by Django 5.2.14 on 2026-05-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_ndisdocument_ndischunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ndis', 'NDIS Pricing Document'), ('policy', 'Company Policy'), ('procedure', 'Standard Operating Procedure'), ('training', 'Training Material'), ('reference', 'Reference Document'), ('other', 'Other Document')], db_index=True, default='other', help_text='Category/type of the document', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('year', models.CharField(blank=True, db_index=True, help_text="Fiscal year or version identifier (e.g., '2024-25')", max_length=20)),
                ('version', models.CharField(blank=True, help_text="e.g., 'v1.3'", max_length=40)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, help_text='Original filename of the uploaded document', max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Only active documents are searched by the chatbot')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('namespace', models.CharField(blank=True, db_index=True, help_text="Pinecone namespace for this document's vectors", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='awards_docu_documen_df4c69_idx'), models.Index(fields=['namespace'], name='awards_docu_namespa_a7cc1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=300)),
                ('page_start', models.PositiveIntegerField(default=0)),
                ('page_end', models.PositiveIntegerField(default=0)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('is_indexed', models.BooleanField(default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='awards.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['vector_id'], name='awards_docu_vector__3af084_idx'), models.Index(fields=['is_indexed'], name='awards_docu_is_inde_a1dc05_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_doc_chunk')],
            },
        ),
    ]
